- name: Install NodeJS
  ansible.builtin.yum:
    name: ["nodejs", "make", "gcc-c++"]
    state: present

- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop
    comment: roboshop user

- name: Download code
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: remove existing code
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy App code
  ansible.builtin.copy:
    src: /tmp/catalogue-main
    dest: /home/roboshop/catalogue
    remote_src: yes
  become_user: roboshop

- name: Install packages based on package.json.
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

